### ISSUE TITLE
[BUG] Failing PerformanceAnalyzerWebServerTest for Java17

### ISSUE THREAD

**Issue by sruti1312** [opensearch-project/performance-analyzer-rca#167]
**What is the bug?**
Failing PerformanceAnalyzerWebServerTest.testUnauthenticatedClientGetsRejected for Java17

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by Tjofil** [comment]
Did some investigation and the test is not failing due to client being able to authenticate and proceed successfully but due to Exception caught not being of SSLException type but SocketException ( Broken pipe ) where startSSLHandshake function is somewhere in the middle of the exception stack trace. This way we catch it the general Exception catch block and throw AssertionError failing the test.

I suspect the handshake implementation changed between versions so that server suddenly closes it's resources at some point and causes the client to read/write to a closed connection which tends to throw previously mentioned "Broken pipe" exception.

Something that backs this up: 
https://bugs.openjdk.org/browse/JDK-8262053

I propose just including the SocketException as the possible cause of the auth fail assertions as the initialization of the server and the rest of the SSL setup seem standard to me.
